"""NO AI SLOP. Spots AI-made videos and AI accounts BEFORE downloading them (cheap, instant):

  1. hashtags / words: #ai #aigenerated #sora2 #veo3 #kling "made with ai" ...
  2. AI tools + AI trends: Sora, Veo, Kling, Hailuo, Midjourney, Grok Imagine, AI babies ...
  3. "Italian brainrot" characters (Tralalero, Tung Tung Sahur, ...): they are all AI-made
  4. account names like "brainrot.ai", "ai_memes", "aivideos"
  5. the site's own "AI-generated" label, when TikTok / Instagram send one

After download the AI judge also looks at the pictures and gives an "ai" score (brain.py).
Accounts caught making AI get blocked for good (db.ai_users).
"""
import re

# hashtags that mean AI (lowercase, only letters/digits)
AI_TAGS = {
    "ai", "aiart", "aiartwork", "aiartist", "aiartcommunity", "aigenerated", "aigeneratedart",
    "aigeneratedvideo", "aigeneratedcontent", "aivideo", "aivideos", "aivideogenerator", "aianimation",
    "aianimations", "aianimated", "aimusic", "aisong", "aisongs", "aicover", "aicovers", "aivoice",
    "aifilter", "aiedit", "aiedits", "aimeme", "aimemes", "aislop", "aibrainrot", "aibaby", "aibabies",
    "aifunny", "aicat", "aicats", "aidog", "aianimals", "aianimal", "aigirl", "aicomedy", "aistory",
    "aistories", "aicreator", "aitrend", "aitools", "aitool", "aimade", "aiface", "aifaceswap",
    "aiphoto", "aiimage", "aiimages", "aiavatar", "aicharacter", "aiinfluencer", "aimodel", "aiasmr",
    "genai", "generativeai", "aigc", "madewithai", "createdwithai", "madebyai", "artificialintelligence",
    "sora", "sora2", "soraai", "soraapp", "openaisora", "openai", "chatgpt", "gpt", "gpt4", "gpt5",
    "veo", "veo2", "veo3", "googleveo", "flowtv", "kling", "klingai", "kling2", "runwayml", "runwaygen3",
    "runwaygen4", "hailuo", "hailuoai", "minimaxai", "pikalabs", "pikaart", "lumaai",
    "dreammachine", "midjourney", "stablediffusion", "sdxl", "dalle", "dalle3", "comfyui", "deforum",
    "animatediff", "higgsfield", "higgsfieldai", "pixverse", "pixverseai", "vidu", "viduai", "hedra",
    "viggle", "viggleai", "heygen", "synthesia", "elevenlabs", "suno", "sunoai", "udio", "grok",
    "grokimagine", "grokai", "seedance", "hunyuan", "wan21", "wan22", "wanai", "deepfake", "deepfakes",
    "faceswap", "talkingbaby", "babypodcast", "fruitloveisland", "fruitdrama", "catsoapopera",
    "bigfootvlog", "yetivlog", "italianbrainrot", "italianbrainrots", "brainrotitaliano",
    "brainrotitalian", "italianbrainrotmemes", "italianbrainrotanimals",
}

# words / phrases anywhere in title, description, tags (word-bounded, any case)
AI_PHRASES = [
    "ai generated", "ai-generated", "generated by ai", "generated with ai", "made with ai",
    "made by ai", "made using ai", "created with ai", "created by ai", "created using ai", "ai made",
    "ai video", "ai videos", "ai art", "ai animation", "ai animated", "ai voice", "ai cover",
    "ai song", "ai music", "ai slop", "ai filter", "ai edit", "ai meme", "ai memes", "ai baby",
    "ai babies", "ai cat", "ai cats", "ai animals", "ai brainrot", "ai story", "ai content",
    "ai creator", "ai tool", "ai image", "ai images", "ai photo", "ai character", "ai influencer",
    "artificial intelligence", "a.i. generated", "text to video", "image to video", "prompt:",
    "sora 2", "sora2", "sora ai", "openai sora", "made with sora", "sora app", "openai", "chatgpt",
    "chat gpt", "veo 3", "veo3", "veo 2", "google veo", "kling ai", "klingai", "kling 2",
    "runwayml", "runway ml", "runway gen", "hailuo", "minimax ai", "pika labs", "pikalabs",
    "luma ai", "dream machine", "midjourney", "stable diffusion", "dall-e", "dalle", "comfyui",
    "deforum", "animatediff", "higgsfield", "pixverse", "vidu ai", "hedra", "viggle", "heygen",
    "synthesia", "elevenlabs", "eleven labs", "suno ai", "udio", "grok imagine", "seedance",
    "hunyuan", "deepfake", "face swap", "faceswap", "talking baby", "baby podcast",
    "fruit love island", "fruit drama", "bigfoot vlog", "yeti vlog", "stormtrooper vlog",
    "italian brainrot", "brainrot italiano", "italian brain rot",
]

# "Italian brainrot" characters: all AI-made. Also fan edits of them = still AI stuff.
AI_CHARACTERS = [
    "tralalero", "tralala tralalero", "bombardiro", "bombardiro crocodilo", "tung tung tung",
    "tung tung sahur",
    "tung sahur", "ta ta ta sahur", "ballerina cappuccina", "cappuccina", "cappuccino assassino",
    "brr brr patapim", "patapim", "lirili larila", "lirili", "larila", "chimpanzini", "bananini",
    "trippi troppi", "boneca ambalabu", "ambalabu", "udin din din", "bombombini", "gusini",
    "frigo camelo", "glorbo fruttodrillo", "fruttodrillo", "la vaca saturno", "saturnita", "garamararam",
    "tim cheese", "espressona signora", "bobrito bandito", "burbaloni", "luliloli", "cocofanto",
    "girafa celestre", "zibra zubra", "trulimero", "trichetrichetto", "graipussi", "tric trac baraboom",
    "orangutini", "ananassini", "blueberrinni", "svinino bombondino", "pot hotspot", "job job job sahur",
    "brri brri bicus", "tigrrullini", "ballerino lololo", "gangster footera", "trulimero trulicina",
    "rhino toasterino", "spijuniro golubiro", "crocodildo", "il cacto hipopotamo", "chef crabracadabra",
    "strawberrelli flamingelli", "tracotucotulu", "los tralaleritos",
]

# never count these as AI (false alarms)
NOT_AI = ["ai hoshino", "hoshino ai", "ai uehara", "ai haibara", "ai ai ai", "ai que", "ai meu",
          "ai mds", "ai credo", "ai caramba", "ai weiwei"]

# account names: parts that mean an AI account
AI_NAME_PARTS = {"ai", "aiart", "aivideo", "aivideos", "aigen", "aigenerated", "aianimation", "aistudio",
                 "aiworld", "aimemes", "aimeme", "aibrainrot", "aislop", "aitok", "aifilms", "aiclips",
                 "aitv", "aiverse", "aicreator", "aivids", "aistories", "aistory", "aicomedy", "aimagic",
                 "aimotion", "aitoons", "sora2", "soraai", "veo3", "klingai", "midjourney", "hailuo",
                 "chatgpt", "openai", "genai", "aigc", "grokimagine", "italianbrainrot", "deepfake",
                 "deepfakes", "aibaby", "aibabies", "aicats", "aianimals"}
_AI_NAME_START = re.compile(
    r"^ai(art|video|vid|gen|anim|meme|brainrot|slop|creator|studio|world|lab|film|clip|short|tok|"
    r"verse|stor|edit|made|magic|motion|daily|fun|cat|dog|bab|animal|tv|channel|content|creation|"
    r"dream|vision|toon|cartoon|comedy|music|song|cover|voice|trend|viral|reel|italian|fruit|kid)")
_AI_NAME_END = re.compile(
    r"(brainrot|meme|memes|video|videos|art|anim|story|stories|clip|clips|edit|edits|fun|funny|"
    r"daily|world|studio|lab|films|creator|tok|gen|animals|cat|cats|dog|dogs|baby|babies|toon|"
    r"toons|comedy|dream|vision|slop|italian|trend|trends|viral|shorts|reels|content|made|"
    r"magic|motion|verse|tv|channel|kids|fruit|fruits)ai$")


def _pat(phrase):
    words = [re.escape(w) for w in phrase.split()]
    return r"(?<![a-z0-9])" + r"[\s_\-.]*".join(words) + r"(?![a-z0-9])"


_PHRASE_RE = re.compile("|".join(_pat(p) for p in AI_PHRASES), re.I)
_CHAR_RE = re.compile("|".join(_pat(p) for p in AI_CHARACTERS), re.I)
_NOT_AI_RE = re.compile("|".join(_pat(p) for p in NOT_AI), re.I)
_TAG_RE = re.compile(r"#([^\s#.,!?:;()\[\]{}\"']+)")
_BIG_AI = re.compile(r"(?<![A-Za-z])(?:AI|A\.I\.)(?![A-Za-z])")


def _norm_tag(t) -> str:
    return re.sub(r"[^a-z0-9]", "", str(t).lower())


def _tags_of(text, tags):
    out = [_norm_tag(t) for t in (tags or [])]
    out += [_norm_tag(t) for t in _TAG_RE.findall(text or "")]
    return [t for t in out if t]


def _mostly_caps(text) -> bool:
    letters = [c for c in text if c.isalpha()]
    return len(letters) > 8 and sum(c.isupper() for c in letters) / len(letters) > 0.6


def text_hit(title="", description="", tags=None) -> str | None:
    """Why the words say AI, or None."""
    text = f"{title or ''}\n{description or ''}"
    clean = _NOT_AI_RE.sub(" ", text)
    for t in _tags_of(clean, tags):
        if t in AI_TAGS:
            return "#" + t
        if t.startswith(("aigenerated", "aiart", "aivideo", "aianimat", "madewithai", "sora2", "veo3",
                         "klingai", "hailuo", "midjourney", "italianbrainrot", "tralalero",
                         "tungtung", "grokimagine", "aislop", "aibrainrot")):
            return "#" + t
    m = _PHRASE_RE.search(clean)
    if m:
        return m.group(0).strip()
    m = _CHAR_RE.search(clean)
    if m:
        return m.group(0).strip() + " (AI character)"
    title_clean = _NOT_AI_RE.sub(" ", title or "")
    if not _mostly_caps(title_clean) and _BIG_AI.search(title_clean):
        return "AI"
    for t in (tags or []):
        t = _NOT_AI_RE.sub(" ", str(t))
        if _PHRASE_RE.search(t) or _CHAR_RE.search(t):
            return str(t)[:40]
    return None


def _name_parts(name):
    name = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", name or "")          # camelCase -> camel Case
    return [p for p in re.split(r"[\s._\-0-9]+", name.lower()) if p]


def name_hit(name) -> str | None:
    """Account names like brainrot.ai / ai_memes / aivideos."""
    if not name:
        return None
    low = str(name).lower()
    if _NOT_AI_RE.search(low.replace(".", " ").replace("_", " ")):
        return None
    parts = _name_parts(str(name))
    joined = "".join(parts)
    if any(p in AI_NAME_PARTS for p in parts):
        return f"account {name}"
    if _AI_NAME_START.match(joined) or _AI_NAME_END.search(joined):
        return f"account {name}"
    if any(w in joined for w in ("aigenerated", "aivideo", "sora2", "veo3", "klingai", "midjourney",
                                  "italianbrainrot", "grokimagine", "aislop", "aibrainrot")):
        return f"account {name}"
    return None


# ------------------------------------------------------- platform labels --
_LABEL_KEY = re.compile(r"aigc|gen_?ai|ai_?generated|aigenerated|(^|_)is_?ai($|_)|ai_?label|"
                        r"ailabel|(^|_)ai_?info$|ai_?content|synthetic|made_?with_?ai|created_?by_?ai")
_LEAF_KEY = re.compile(r"label|type|method|(^|_)is_|created|generated|flag|status|aigc|ai|desc")
_FALSY = {"", "0", "false", "none", "null", "no", "not_ai", "unknown", "n/a", "not_detected", "0.0"}


def _snake(k) -> str:
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", str(k)).lower()


def _truthy(v, depth=0) -> bool:
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return v != 0
    if isinstance(v, str):
        return v.strip().lower() not in _FALSY
    if isinstance(v, dict) and depth < 3:
        return any(_LEAF_KEY.search(_snake(k)) and _truthy(x, depth + 1) for k, x in v.items())
    if isinstance(v, list) and depth < 3:
        return any(_truthy(x, depth + 1) for x in v[:10])
    return False


def label_hit(obj, depth=0) -> str | None:
    """The site's own "AI-generated" label, if TikTok / Instagram put one in their data."""
    if depth > 6:
        return None
    if isinstance(obj, dict):
        for k, v in obj.items():
            sk = _snake(k)
            if "cover" in sk or "dynamic" in sk:
                continue                   # tikwm "ai_dynamic_cover" is just a moving thumbnail
            if _LABEL_KEY.search(sk) and _truthy(v):
                return f"site label '{k}'"
            if isinstance(v, (dict, list)):
                r = label_hit(v, depth + 1)
                if r:
                    return r
    elif isinstance(obj, list):
        for v in obj[:50]:
            r = label_hit(v, depth + 1)
            if r:
                return r
    return None


def check(meta: dict) -> str | None:
    """Short reason why this video looks like AI stuff, or None if it looks human-made."""
    return (meta.get("ai_label")
            or text_hit(meta.get("title"), meta.get("description"), meta.get("tags"))
            or name_hit(meta.get("uploader")))


def speech_hit(transcript) -> str | None:
    """What the video SAYS (ear mode): AI characters or "made with AI"."""
    clean = _NOT_AI_RE.sub(" ", transcript or "")
    m = _CHAR_RE.search(clean) or _PHRASE_RE.search(clean)
    return f"says '{m.group(0).strip()}'" if m else None


def query_is_ai(q) -> bool:
    """User typed an AI topic (e.g. 'italian brainrot'): tell them we will skip AI stuff."""
    return bool(text_hit(q))
